### ISSUE TITLE
Архитектура приложения

### ISSUE THREAD

**Issue by aorgish** [dm-grinko/game-snake#1]
Весь код находиться в одном файле main.js, там смешано все. Лучше выделить в отдельный файл движок игры, который можно будет прикрутить к любому UI, и будет возможность тестировать. И отдельно выделить в файл работу с DOM.  Например смотри https://github.com/aorgish/tic-tac-toe , там data.js - это собственно сам движок, и dom.js - все UI методы для отображения.

**Comment by dm-grinko** [comment]
Спасибо. Исправил.
